/**
 * The Continuity icon index: every icon's name, category, search tags, and
 * the lucide-react names it replaces. Pure data with no imports, like
 * `./nodes.ts`, so the build script and tests can read it under `node`.
 *
 * `name` is the kebab-case id used for the SVG file (`arrow-right.svg`); the
 * component is its PascalCase plus `Icon` (`ArrowRightIcon`), and the
 * geometry is the camelCase export of `./nodes.ts` unless `node` says
 * otherwise (only where the name is a reserved word).
 */

export const ICON_CATEGORIES = [
  'product',
  'arrows',
  'actions',
  'status',
  'interface',
  'communication',
  'people',
  'security',
  'files',
  'media',
  'devices',
  'data',
  'development',
  'objects',
  'commerce',
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];

export interface IconManifestEntry {
  /** Kebab-case id: the SVG file name and the key in `icons.json`. */
  readonly name: string;
  readonly category: IconCategory;
  /** Extra search words, beyond the name itself. */
  readonly tags: readonly string[];
  /** lucide-react names (without the `Icon` suffix) this icon replaces. */
  readonly lucide: readonly string[];
  /** The `./nodes.ts` export, when it is not the camelCase of `name`. */
  readonly node?: string;
}

export const ICON_MANIFEST: readonly IconManifestEntry[] = [
  // Product: the things Stunt Double is made of.
  {
    name: 'actor',
    category: 'product',
    tags: ['persona', 'ai user', 'cast', 'person'],
    lucide: [],
  },
  { name: 'checklist', category: 'product', tags: ['verify', 'flow', 'steps', 'test'], lucide: [] },
  { name: 'run', category: 'product', tags: ['start', 'execute', 'go', 'take'], lucide: [] },
  {
    name: 'interview',
    category: 'product',
    tags: ['research', 'quote', 'conversation', 'study'],
    lucide: ['MessageSquareQuote'],
  },
  {
    name: 'automation',
    category: 'product',
    tags: ['workflow', 'trigger', 'schedule', 'graph'],
    lucide: [],
  },
  {
    name: 'evidence',
    category: 'product',
    tags: ['screenshot', 'capture', 'proof', 'artefact'],
    lucide: [],
  },
  { name: 'insight', category: 'product', tags: ['finding', 'lamp', 'idea', 'theme'], lucide: [] },
  { name: 'feedback', category: 'product', tags: ['comment', 'widget', 'pin', 'note'], lucide: [] },
  {
    name: 'worker',
    category: 'product',
    tags: ['self-hosted', 'chip', 'browser', 'compute'],
    lucide: [],
  },
  { name: 'project', category: 'product', tags: ['case', 'production', 'workspace'], lucide: [] },
  {
    name: 'knowledge',
    category: 'product',
    tags: ['notebook', 'facts', 'credentials', 'memory'],
    lucide: [],
  },
  {
    name: 'take',
    category: 'product',
    tags: ['stamp', 'attempt', 'number', 'version'],
    lucide: [],
  },
  {
    name: 'live-view',
    category: 'product',
    tags: ['watch', 'stream', 'recording', 'screen'],
    lucide: [],
  },
  {
    name: 'design-review',
    category: 'product',
    tags: ['figma', 'frame', 'look', 'critique'],
    lucide: [],
  },
  { name: 'topology', category: 'product', tags: ['sitemap', 'crawl', 'pages', 'map'], lucide: [] },
  { name: 'step', category: 'product', tags: ['number', 'one', 'sequence', 'move'], lucide: [] },
  {
    name: 'assist',
    category: 'product',
    tags: ['request input', 'help', 'hand over', 'pointer'],
    lucide: [],
  },

  // Arrows
  {
    name: 'arrow-right',
    category: 'arrows',
    tags: ['next', 'forward', 'continue'],
    lucide: ['ArrowRight', 'MoveRight'],
  },
  {
    name: 'arrow-left',
    category: 'arrows',
    tags: ['back', 'previous'],
    lucide: ['ArrowLeft', 'MoveLeft'],
  },
  { name: 'arrow-up', category: 'arrows', tags: ['increase', 'top'], lucide: ['ArrowUp'] },
  { name: 'arrow-down', category: 'arrows', tags: ['decrease', 'bottom'], lucide: ['ArrowDown'] },
  {
    name: 'arrow-up-right',
    category: 'arrows',
    tags: ['open', 'outbound', 'link'],
    lucide: ['ArrowUpRight'],
  },
  {
    name: 'arrow-down-right',
    category: 'arrows',
    tags: ['inbound', 'decline'],
    lucide: ['ArrowDownRight'],
  },
  { name: 'arrow-up-down', category: 'arrows', tags: ['sort', 'order'], lucide: ['ArrowUpDown'] },
  { name: 'arrow-down-up', category: 'arrows', tags: ['sort', 'swap'], lucide: ['ArrowDownUp'] },
  {
    name: 'chevron-right',
    category: 'arrows',
    tags: ['next', 'expand', 'caret'],
    lucide: ['ChevronRight'],
  },
  {
    name: 'chevron-left',
    category: 'arrows',
    tags: ['previous', 'back', 'caret'],
    lucide: ['ChevronLeft'],
  },
  { name: 'chevron-up', category: 'arrows', tags: ['collapse', 'caret'], lucide: ['ChevronUp'] },
  {
    name: 'chevron-down',
    category: 'arrows',
    tags: ['expand', 'dropdown', 'caret'],
    lucide: ['ChevronDown'],
  },
  {
    name: 'chevrons-up-down',
    category: 'arrows',
    tags: ['select', 'combobox', 'sort'],
    lucide: ['ChevronsUpDown'],
  },
  {
    name: 'chevrons-down-up',
    category: 'arrows',
    tags: ['collapse all', 'fold'],
    lucide: ['ChevronsDownUp'],
  },
  {
    name: 'corner-down-left',
    category: 'arrows',
    tags: ['enter', 'return', 'submit'],
    lucide: ['CornerDownLeft'],
  },
  {
    name: 'external-link',
    category: 'arrows',
    tags: ['open', 'new tab', 'outbound'],
    lucide: ['ExternalLink', 'SquareArrowOutUpRight'],
  },
  {
    name: 'trending-up',
    category: 'arrows',
    tags: ['growth', 'increase', 'chart'],
    lucide: ['TrendingUp'],
  },
  {
    name: 'trending-down',
    category: 'arrows',
    tags: ['decline', 'decrease', 'chart'],
    lucide: ['TrendingDown'],
  },
  {
    name: 'refresh',
    category: 'arrows',
    tags: ['reload', 'sync', 're-run'],
    lucide: ['RefreshCw', 'RefreshCcw'],
  },
  {
    name: 'rotate-ccw',
    category: 'arrows',
    tags: ['undo', 'reset', 'revert'],
    lucide: ['RotateCcw', 'Undo2'],
  },
  { name: 'rotate-cw', category: 'arrows', tags: ['redo', 'retry'], lucide: ['RotateCw', 'Redo2'] },
  {
    name: 'repeat',
    category: 'arrows',
    tags: ['loop', 'recurring', 'again'],
    lucide: ['Repeat', 'Repeat2'],
  },
  {
    name: 'history',
    category: 'arrows',
    tags: ['past', 'versions', 'log', 'time'],
    lucide: ['History'],
  },
  {
    name: 'shrink',
    category: 'arrows',
    tags: ['minimise', 'collapse', 'exit fullscreen'],
    lucide: ['Shrink', 'Minimize2'],
  },
  {
    name: 'expand',
    category: 'arrows',
    tags: ['maximise', 'fullscreen', 'enlarge'],
    lucide: ['Expand', 'Maximize2'],
  },
  {
    name: 'navigation',
    category: 'arrows',
    tags: ['direction', 'go to', 'navigate'],
    lucide: ['Navigation'],
  },

  // Actions
  { name: 'plus', category: 'actions', tags: ['add', 'new', 'create'], lucide: ['Plus'] },
  { name: 'minus', category: 'actions', tags: ['remove', 'subtract'], lucide: ['Minus'] },
  { name: 'x', category: 'actions', tags: ['close', 'dismiss', 'cancel', 'clear'], lucide: ['X'] },
  {
    name: 'check',
    category: 'actions',
    tags: ['done', 'confirm', 'tick', 'pass'],
    lucide: ['Check'],
  },
  {
    name: 'search',
    category: 'actions',
    tags: ['find', 'magnifier', 'look up'],
    lucide: ['Search'],
  },
  { name: 'search-x', category: 'actions', tags: ['no results', 'not found'], lucide: ['SearchX'] },
  {
    name: 'scan-search',
    category: 'actions',
    tags: ['inspect', 'scan', 'audit'],
    lucide: ['ScanSearch'],
  },
  {
    name: 'trash',
    category: 'actions',
    tags: ['delete', 'remove', 'bin'],
    lucide: ['Trash', 'Trash2'],
  },
  { name: 'copy', category: 'actions', tags: ['duplicate', 'clone'], lucide: ['Copy'] },
  { name: 'clipboard', category: 'actions', tags: ['paste', 'board'], lucide: ['Clipboard'] },
  {
    name: 'clipboard-check',
    category: 'actions',
    tags: ['copied', 'checklist', 'done'],
    lucide: ['ClipboardCheck'],
  },
  {
    name: 'clipboard-list',
    category: 'actions',
    tags: ['tasks', 'plan', 'items'],
    lucide: ['ClipboardList'],
  },
  {
    name: 'clipboard-copy',
    category: 'actions',
    tags: ['copy to clipboard'],
    lucide: ['ClipboardCopy'],
  },
  { name: 'pencil', category: 'actions', tags: ['edit', 'write', 'rename'], lucide: ['Pencil'] },
  {
    name: 'pencil-line',
    category: 'actions',
    tags: ['edit', 'annotate', 'sign'],
    lucide: ['PencilLine', 'PenLine'],
  },
  {
    name: 'edit',
    category: 'actions',
    tags: ['compose', 'new message', 'write'],
    lucide: ['SquarePen', 'PenSquare', 'Edit'],
  },
  { name: 'download', category: 'actions', tags: ['save', 'export'], lucide: ['Download'] },
  { name: 'upload', category: 'actions', tags: ['import', 'attach'], lucide: ['Upload'] },
  {
    name: 'send',
    category: 'actions',
    tags: ['submit', 'message', 'paper plane'],
    lucide: ['Send', 'SendHorizontal'],
  },
  {
    name: 'share',
    category: 'actions',
    tags: ['distribute', 'nodes'],
    lucide: ['Share2', 'Share'],
  },
  {
    name: 'link',
    category: 'actions',
    tags: ['url', 'chain', 'connect'],
    lucide: ['Link', 'Link2'],
  },
  {
    name: 'link-off',
    category: 'actions',
    tags: ['unlink', 'disconnect'],
    lucide: ['Link2Off', 'Unlink'],
  },
  { name: 'filter', category: 'actions', tags: ['funnel', 'refine'], lucide: ['Filter', 'Funnel'] },
  {
    name: 'list-filter',
    category: 'actions',
    tags: ['filter', 'narrow', 'sort'],
    lucide: ['ListFilter'],
  },
  {
    name: 'sliders',
    category: 'actions',
    tags: ['adjust', 'controls', 'preferences'],
    lucide: ['SlidersHorizontal'],
  },
  { name: 'archive', category: 'actions', tags: ['store', 'box', 'hide'], lucide: ['Archive'] },
  {
    name: 'archive-restore',
    category: 'actions',
    tags: ['unarchive', 'restore'],
    lucide: ['ArchiveRestore'],
  },
  { name: 'log-out', category: 'actions', tags: ['sign out', 'exit', 'leave'], lucide: ['LogOut'] },
  {
    name: 'door-open',
    category: 'actions',
    tags: ['enter', 'onboarding', 'welcome'],
    lucide: ['DoorOpen'],
  },
  { name: 'printer', category: 'actions', tags: ['print', 'pdf'], lucide: ['Printer'] },
  { name: 'paperclip', category: 'actions', tags: ['attach', 'attachment'], lucide: ['Paperclip'] },
  {
    name: 'grip-vertical',
    category: 'actions',
    tags: ['drag', 'reorder', 'handle'],
    lucide: ['GripVertical'],
  },
  {
    name: 'more-horizontal',
    category: 'actions',
    tags: ['ellipsis', 'menu', 'overflow'],
    lucide: ['MoreHorizontal', 'Ellipsis'],
  },
  {
    name: 'more-vertical',
    category: 'actions',
    tags: ['ellipsis', 'menu', 'overflow'],
    lucide: ['MoreVertical', 'EllipsisVertical'],
  },
  { name: 'bookmark', category: 'actions', tags: ['save', 'keep'], lucide: ['Bookmark'] },
  { name: 'bookmark-plus', category: 'actions', tags: ['save', 'add'], lucide: ['BookmarkPlus'] },
  { name: 'tag', category: 'actions', tags: ['label', 'price'], lucide: ['Tag'] },
  {
    name: 'sparkles',
    category: 'actions',
    tags: ['ai', 'generate', 'suggest', 'magic'],
    lucide: ['Sparkles'],
  },
  {
    name: 'wand',
    category: 'actions',
    tags: ['generate', 'auto', 'magic'],
    lucide: ['WandSparkles', 'Wand'],
  },
  { name: 'play', category: 'actions', tags: ['start', 'run', 'video'], lucide: ['Play'] },
  {
    name: 'play-circle',
    category: 'actions',
    tags: ['watch', 'video', 'start'],
    lucide: ['PlayCircle', 'CirclePlay'],
  },
  { name: 'pause', category: 'actions', tags: ['hold', 'video', 'halt'], lucide: ['Pause'] },
  {
    name: 'stop',
    category: 'actions',
    tags: ['end', 'halt', 'cancel run', 'take mark'],
    lucide: ['CircleStop', 'StopCircle'],
  },
  {
    name: 'hand',
    category: 'actions',
    tags: ['stop', 'raise', 'take over', 'wave'],
    lucide: ['Hand'],
  },
  {
    name: 'pointer',
    category: 'actions',
    tags: ['cursor', 'mouse', 'select'],
    lucide: ['MousePointer2', 'MousePointer'],
  },
  {
    name: 'pointer-click',
    category: 'actions',
    tags: ['click', 'cursor', 'interact'],
    lucide: ['MousePointerClick'],
  },
  {
    name: 'pending',
    category: 'actions',
    tags: ['loading', 'waiting', 'in progress', 'queued'],
    lucide: ['Loader', 'Loader2', 'LoaderCircle'],
  },

  // Status
  {
    name: 'circle',
    category: 'status',
    tags: ['empty', 'not started', 'radio'],
    lucide: ['Circle'],
  },
  {
    name: 'circle-dot',
    category: 'status',
    tags: ['current', 'active', 'selected'],
    lucide: ['CircleDot'],
  },
  {
    name: 'circle-dashed',
    category: 'status',
    tags: ['queued', 'draft', 'pending'],
    lucide: ['CircleDashed'],
  },
  { name: 'square', category: 'status', tags: ['stop', 'shape', 'unchecked'], lucide: ['Square'] },
  {
    name: 'check-circle',
    category: 'status',
    tags: ['success', 'passed', 'complete'],
    lucide: ['CheckCircle', 'CheckCircle2', 'CircleCheck', 'CircleCheckBig'],
  },
  {
    name: 'x-circle',
    category: 'status',
    tags: ['failed', 'error', 'cancel'],
    lucide: ['XCircle', 'CircleX'],
  },
  {
    name: 'minus-circle',
    category: 'status',
    tags: ['skipped', 'remove', 'neutral'],
    lucide: ['MinusCircle', 'CircleMinus'],
  },
  {
    name: 'plus-circle',
    category: 'status',
    tags: ['add', 'new'],
    lucide: ['PlusCircle', 'CirclePlus'],
  },
  { name: 'info', category: 'status', tags: ['about', 'detail', 'note'], lucide: ['Info'] },
  {
    name: 'help',
    category: 'status',
    tags: ['question', 'support', 'faq'],
    lucide: ['HelpCircle', 'CircleHelp'],
  },
  {
    name: 'alert-circle',
    category: 'status',
    tags: ['error', 'attention', 'warning'],
    lucide: ['AlertCircle', 'CircleAlert'],
  },
  {
    name: 'alert-triangle',
    category: 'status',
    tags: ['warning', 'caution', 'danger'],
    lucide: ['AlertTriangle', 'TriangleAlert'],
  },
  {
    name: 'octagon-x',
    category: 'status',
    tags: ['stop', 'blocked', 'fatal'],
    lucide: ['OctagonX', 'XOctagon'],
  },
  { name: 'ban', category: 'status', tags: ['forbidden', 'blocked', 'disabled'], lucide: ['Ban'] },
  {
    name: 'badge-check',
    category: 'status',
    tags: ['verified', 'approved', 'certified'],
    lucide: ['BadgeCheck'],
  },
  {
    name: 'flag',
    category: 'status',
    tags: ['report', 'mark', 'milestone'],
    lucide: ['Flag', 'FlagTriangleRight'],
  },
  { name: 'bell', category: 'status', tags: ['notification', 'alert'], lucide: ['Bell'] },
  {
    name: 'bell-ring',
    category: 'status',
    tags: ['notification', 'ringing', 'reminder'],
    lucide: ['BellRing'],
  },
  { name: 'clock', category: 'status', tags: ['time', 'duration', 'schedule'], lucide: ['Clock'] },
  { name: 'calendar', category: 'status', tags: ['date', 'schedule', 'day'], lucide: ['Calendar'] },
  {
    name: 'calendar-clock',
    category: 'status',
    tags: ['scheduled', 'due', 'cron'],
    lucide: ['CalendarClock'],
  },
  {
    name: 'timer',
    category: 'status',
    tags: ['stopwatch', 'duration', 'limit'],
    lucide: ['Timer'],
  },
  {
    name: 'gauge',
    category: 'status',
    tags: ['score', 'speed', 'meter', 'performance'],
    lucide: ['Gauge'],
  },

  // Interface
  {
    name: 'menu',
    category: 'interface',
    tags: ['hamburger', 'navigation', 'lines'],
    lucide: ['Menu'],
  },
  {
    name: 'settings',
    category: 'interface',
    tags: ['gear', 'cog', 'preferences'],
    lucide: ['Settings', 'Cog'],
  },
  {
    name: 'layout-dashboard',
    category: 'interface',
    tags: ['dashboard', 'overview', 'home'],
    lucide: ['LayoutDashboard'],
  },
  {
    name: 'layout-grid',
    category: 'interface',
    tags: ['grid', 'gallery', 'tiles'],
    lucide: ['LayoutGrid'],
  },
  { name: 'list', category: 'interface', tags: ['rows', 'bullets'], lucide: ['List'] },
  {
    name: 'list-checks',
    category: 'interface',
    tags: ['tasks', 'checklist', 'todo'],
    lucide: ['ListChecks'],
  },
  {
    name: 'square-check',
    category: 'interface',
    tags: ['checkbox', 'checked', 'done'],
    lucide: ['SquareCheck', 'CheckSquare'],
  },
  {
    name: 'square-kanban',
    category: 'interface',
    tags: ['board', 'columns'],
    lucide: ['SquareKanban'],
  },
  {
    name: 'app-window',
    category: 'interface',
    tags: ['browser', 'window', 'app'],
    lucide: ['AppWindow'],
  },
  {
    name: 'panels-top-left',
    category: 'interface',
    tags: ['layout', 'sidebar', 'template'],
    lucide: ['PanelsTopLeft'],
  },
  {
    name: 'panel-right-open',
    category: 'interface',
    tags: ['sidebar', 'drawer', 'show'],
    lucide: ['PanelRightOpen'],
  },
  {
    name: 'panel-right-close',
    category: 'interface',
    tags: ['sidebar', 'drawer', 'hide'],
    lucide: ['PanelRightClose'],
  },
  {
    name: 'frame',
    category: 'interface',
    tags: ['figma frame', 'artboard', 'crop'],
    lucide: ['Frame'],
  },
  { name: 'layers', category: 'interface', tags: ['stack', 'levels'], lucide: ['Layers'] },
  {
    name: 'blocks',
    category: 'interface',
    tags: ['integrations', 'apps', 'modules'],
    lucide: ['Blocks'],
  },
  {
    name: 'component',
    category: 'interface',
    tags: ['design system', 'symbol', 'figma'],
    lucide: ['Component'],
  },
  {
    name: 'keyboard',
    category: 'interface',
    tags: ['shortcuts', 'type', 'keys'],
    lucide: ['Keyboard'],
  },
  {
    name: 'command',
    category: 'interface',
    tags: ['shortcut', 'cmd', 'palette'],
    lucide: ['Command'],
  },
  { name: 'hash', category: 'interface', tags: ['channel', 'number', 'slack'], lucide: ['Hash'] },
  { name: 'type', category: 'interface', tags: ['text', 'font', 'typography'], lucide: ['Type'] },
  {
    name: 'text-cursor-input',
    category: 'interface',
    tags: ['input', 'field', 'type'],
    lucide: ['TextCursorInput'],
  },
  {
    name: 'form-input',
    category: 'interface',
    tags: ['field', 'input', 'form'],
    lucide: ['FormInput'],
  },
  { name: 'sun', category: 'interface', tags: ['light mode', 'theme', 'day'], lucide: ['Sun'] },
  { name: 'moon', category: 'interface', tags: ['dark mode', 'theme', 'night'], lucide: ['Moon'] },
  {
    name: 'contrast',
    category: 'interface',
    tags: ['accessibility', 'theme', 'half'],
    lucide: ['Contrast'],
  },
  {
    name: 'palette',
    category: 'interface',
    tags: ['colour', 'brand', 'theme'],
    lucide: ['Palette'],
  },
  {
    name: 'accessibility',
    category: 'interface',
    tags: ['a11y', 'person', 'inclusive'],
    lucide: ['Accessibility'],
  },
  {
    name: 'languages',
    category: 'interface',
    tags: ['translate', 'locale', 'i18n'],
    lucide: ['Languages'],
  },

  // Communication
  {
    name: 'message-square',
    category: 'communication',
    tags: ['chat', 'comment', 'bubble'],
    lucide: ['MessageSquare'],
  },
  {
    name: 'message-square-text',
    category: 'communication',
    tags: ['chat', 'transcript', 'note'],
    lucide: ['MessageSquareText'],
  },
  {
    name: 'message-square-more',
    category: 'communication',
    tags: ['typing', 'chat', 'reply'],
    lucide: ['MessageSquareMore'],
  },
  {
    name: 'message-square-plus',
    category: 'communication',
    tags: ['new chat', 'add comment'],
    lucide: ['MessageSquarePlus'],
  },
  {
    name: 'messages-square',
    category: 'communication',
    tags: ['conversation', 'thread', 'chat'],
    lucide: ['MessagesSquare'],
  },
  {
    name: 'quote',
    category: 'communication',
    tags: ['said', 'verbatim', 'testimonial', 'blockquote'],
    lucide: ['Quote', 'TextQuote'],
  },
  {
    name: 'message-circle',
    category: 'communication',
    tags: ['chat', 'reply', 'bubble'],
    lucide: ['MessageCircle'],
  },
  {
    name: 'mail',
    category: 'communication',
    tags: ['email', 'envelope', 'inbox'],
    lucide: ['Mail'],
  },
  {
    name: 'mail-open',
    category: 'communication',
    tags: ['read', 'email', 'envelope'],
    lucide: ['MailOpen'],
  },
  {
    name: 'inbox',
    category: 'communication',
    tags: ['tray', 'notifications', 'queue'],
    lucide: ['Inbox'],
  },
  {
    name: 'megaphone',
    category: 'communication',
    tags: ['announce', 'broadcast', 'marketing'],
    lucide: ['Megaphone'],
  },
  {
    name: 'globe',
    category: 'communication',
    tags: ['web', 'website', 'world', 'url'],
    lucide: ['Globe'],
  },
  {
    name: 'life-buoy',
    category: 'communication',
    tags: ['support', 'help', 'rescue'],
    lucide: ['LifeBuoy'],
  },

  // People
  {
    name: 'user',
    category: 'people',
    tags: ['person', 'account', 'profile'],
    lucide: ['User', 'UserRound'],
  },
  {
    name: 'users',
    category: 'people',
    tags: ['team', 'members', 'group'],
    lucide: ['Users', 'UsersRound'],
  },
  { name: 'user-plus', category: 'people', tags: ['invite', 'add member'], lucide: ['UserPlus'] },
  { name: 'bot', category: 'people', tags: ['agent', 'assistant', 'robot'], lucide: ['Bot'] },
  { name: 'brain', category: 'people', tags: ['memory', 'think', 'model'], lucide: ['Brain'] },
  {
    name: 'fingerprint',
    category: 'people',
    tags: ['identity', 'biometric', 'unique'],
    lucide: ['Fingerprint'],
  },

  // Security
  {
    name: 'shield',
    category: 'security',
    tags: ['protect', 'security', 'guard'],
    lucide: ['Shield'],
  },
  {
    name: 'shield-check',
    category: 'security',
    tags: ['secure', 'verified', 'safe'],
    lucide: ['ShieldCheck'],
  },
  {
    name: 'shield-off',
    category: 'security',
    tags: ['unprotected', 'disabled'],
    lucide: ['ShieldOff'],
  },
  { name: 'lock', category: 'security', tags: ['private', 'locked', 'secure'], lucide: ['Lock'] },
  {
    name: 'lock-open',
    category: 'security',
    tags: ['unlocked', 'public', 'open'],
    lucide: ['LockOpen', 'Unlock'],
  },
  {
    name: 'key',
    category: 'security',
    tags: ['credentials', 'api key', 'password'],
    lucide: ['KeyRound', 'Key'],
  },
  {
    name: 'eye',
    category: 'security',
    tags: ['view', 'show', 'visible', 'watch'],
    lucide: ['Eye'],
  },
  {
    name: 'eye-off',
    category: 'security',
    tags: ['hide', 'hidden', 'invisible'],
    lucide: ['EyeOff'],
  },

  // Files
  { name: 'file', category: 'files', tags: ['document', 'page'], lucide: ['File'] },
  {
    name: 'file-text',
    category: 'files',
    tags: ['document', 'report', 'text'],
    lucide: ['FileText'],
  },
  {
    name: 'file-check',
    category: 'files',
    tags: ['approved', 'done', 'document'],
    lucide: ['FileCheck', 'FileCheck2'],
  },
  {
    name: 'file-chart',
    category: 'files',
    tags: ['report', 'analytics', 'document'],
    lucide: ['FileBarChart', 'FileChartColumn'],
  },
  { name: 'file-json', category: 'files', tags: ['code', 'data', 'braces'], lucide: ['FileJson'] },
  {
    name: 'file-search',
    category: 'files',
    tags: ['find', 'document', 'audit'],
    lucide: ['FileSearch'],
  },
  {
    name: 'file-pen',
    category: 'files',
    tags: ['edit document', 'draft'],
    lucide: ['FileEdit', 'FilePen'],
  },
  { name: 'folder', category: 'files', tags: ['directory', 'collection'], lucide: ['Folder'] },
  { name: 'folder-plus', category: 'files', tags: ['new folder', 'add'], lucide: ['FolderPlus'] },
  {
    name: 'folder-kanban',
    category: 'files',
    tags: ['project', 'board'],
    lucide: ['FolderKanban'],
  },
  { name: 'book-open', category: 'files', tags: ['docs', 'read', 'guide'], lucide: ['BookOpen'] },
  {
    name: 'book-marked',
    category: 'files',
    tags: ['guidelines', 'reference', 'saved'],
    lucide: ['BookMarked'],
  },
  {
    name: 'library',
    category: 'files',
    tags: ['books', 'collection', 'resources'],
    lucide: ['LibraryBig', 'Library'],
  },
  {
    name: 'newspaper',
    category: 'files',
    tags: ['news', 'blog', 'changelog', 'article'],
    lucide: ['Newspaper'],
  },
  {
    name: 'scroll-text',
    category: 'files',
    tags: ['terms', 'contract', 'log'],
    lucide: ['ScrollText'],
  },

  // Media
  { name: 'image', category: 'media', tags: ['picture', 'photo', 'screenshot'], lucide: ['Image'] },
  { name: 'image-plus', category: 'media', tags: ['add image', 'upload'], lucide: ['ImagePlus'] },
  {
    name: 'camera',
    category: 'media',
    tags: ['capture', 'photo', 'screenshot'],
    lucide: ['Camera'],
  },
  {
    name: 'mic',
    category: 'media',
    tags: ['microphone', 'voice', 'dictate', 'speech'],
    lucide: ['Mic'],
  },
  { name: 'film', category: 'media', tags: ['video', 'recording', 'reel'], lucide: ['Film'] },
  {
    name: 'clapperboard',
    category: 'media',
    tags: ['slate', 'scene', 'video'],
    lucide: ['Clapperboard'],
  },
  {
    name: 'monitor-play',
    category: 'media',
    tags: ['video', 'replay', 'demo'],
    lucide: ['MonitorPlay'],
  },
  { name: 'pen-tool', category: 'media', tags: ['vector', 'design', 'draw'], lucide: ['PenTool'] },
  {
    name: 'ruler',
    category: 'media',
    tags: ['measure', 'spacing', 'dimensions'],
    lucide: ['Ruler'],
  },

  // Devices
  {
    name: 'monitor',
    category: 'devices',
    tags: ['desktop', 'screen', 'display'],
    lucide: ['Monitor'],
  },
  {
    name: 'monitor-off',
    category: 'devices',
    tags: ['offline', 'no screen'],
    lucide: ['MonitorOff'],
  },
  { name: 'smartphone', category: 'devices', tags: ['mobile', 'phone'], lucide: ['Smartphone'] },
  { name: 'tablet', category: 'devices', tags: ['ipad', 'device'], lucide: ['Tablet'] },
  {
    name: 'server',
    category: 'devices',
    tags: ['host', 'infrastructure', 'rack'],
    lucide: ['Server'],
  },
  {
    name: 'database',
    category: 'devices',
    tags: ['storage', 'data', 'table'],
    lucide: ['Database'],
  },

  // Data
  {
    name: 'chart-bar',
    category: 'data',
    tags: ['analytics', 'bars', 'report'],
    lucide: ['BarChart3', 'BarChart', 'ChartColumn'],
  },
  {
    name: 'chart-column',
    category: 'data',
    tags: ['analytics', 'bars', 'usage'],
    lucide: ['ChartNoAxesColumn', 'BarChart2'],
  },
  {
    name: 'chart-line',
    category: 'data',
    tags: ['analytics', 'trend', 'graph'],
    lucide: ['LineChart', 'ChartLine'],
  },
  {
    name: 'activity',
    category: 'data',
    tags: ['pulse', 'heartbeat', 'events'],
    lucide: ['Activity'],
  },
  { name: 'target', category: 'data', tags: ['goal', 'aim', 'objective'], lucide: ['Target'] },

  // Development
  {
    name: 'terminal',
    category: 'development',
    tags: ['cli', 'shell', 'prompt'],
    lucide: ['Terminal'],
  },
  {
    name: 'square-terminal',
    category: 'development',
    tags: ['cli', 'console', 'shell'],
    lucide: ['SquareTerminal'],
  },
  {
    name: 'code',
    category: 'development',
    tags: ['source', 'embed', 'brackets'],
    lucide: ['Code'],
  },
  {
    name: 'git-branch',
    category: 'development',
    tags: ['repository', 'version', 'branch'],
    lucide: ['GitBranch'],
  },
  {
    name: 'git-pull-request',
    category: 'development',
    tags: ['pr', 'merge', 'review'],
    lucide: ['GitPullRequest'],
  },
  {
    name: 'workflow',
    category: 'development',
    tags: ['flow', 'pipeline', 'automation'],
    lucide: ['Workflow'],
  },
  {
    name: 'network',
    category: 'development',
    tags: ['tree', 'hierarchy', 'topology'],
    lucide: ['Network'],
  },
  { name: 'route', category: 'development', tags: ['path', 'journey', 'flow'], lucide: ['Route'] },
  {
    name: 'plug',
    category: 'development',
    tags: ['integration', 'connect', 'mcp'],
    lucide: ['Plug'],
  },
  { name: 'bug', category: 'development', tags: ['issue', 'defect', 'error'], lucide: ['Bug'] },
  {
    name: 'package',
    category: 'development',
    tags: ['box', 'release', 'bundle'],
    lucide: ['Package'],
    node: 'packageBox',
  },
  {
    name: 'flask',
    category: 'development',
    tags: ['experiment', 'lab', 'beta'],
    lucide: ['FlaskConical'],
  },
  {
    name: 'wrench',
    category: 'development',
    tags: ['tool', 'fix', 'configure'],
    lucide: ['Wrench'],
  },
  {
    name: 'rocket',
    category: 'development',
    tags: ['launch', 'deploy', 'ship'],
    lucide: ['Rocket'],
  },
  {
    name: 'zap',
    category: 'development',
    tags: ['fast', 'trigger', 'power', 'lightning'],
    lucide: ['Zap'],
  },

  // Objects and places
  { name: 'home', category: 'objects', tags: ['house', 'start'], lucide: ['Home', 'House'] },
  {
    name: 'building',
    category: 'objects',
    tags: ['company', 'office', 'organisation'],
    lucide: ['Building'],
  },
  {
    name: 'buildings',
    category: 'objects',
    tags: ['enterprise', 'company', 'city'],
    lucide: ['Building2'],
  },
  { name: 'store', category: 'objects', tags: ['shop', 'marketplace'], lucide: ['Store'] },
  {
    name: 'map-pin',
    category: 'objects',
    tags: ['location', 'place', 'marker'],
    lucide: ['MapPin'],
  },
  {
    name: 'compass',
    category: 'objects',
    tags: ['explore', 'direction', 'discover'],
    lucide: ['Compass'],
  },
  { name: 'scale', category: 'objects', tags: ['legal', 'balance', 'compare'], lucide: ['Scale'] },
  {
    name: 'brick-wall',
    category: 'objects',
    tags: ['blocker', 'firewall', 'barrier'],
    lucide: ['BrickWall'],
  },
  {
    name: 'lightbulb',
    category: 'objects',
    tags: ['idea', 'tip', 'suggestion'],
    lucide: ['Lightbulb'],
  },
  { name: 'gift', category: 'objects', tags: ['present', 'reward', 'referral'], lucide: ['Gift'] },
  { name: 'flame', category: 'objects', tags: ['hot', 'streak', 'popular'], lucide: ['Flame'] },

  // Commerce
  {
    name: 'credit-card',
    category: 'commerce',
    tags: ['payment', 'billing', 'card'],
    lucide: ['CreditCard'],
  },
  {
    name: 'shopping-cart',
    category: 'commerce',
    tags: ['basket', 'checkout', 'buy'],
    lucide: ['ShoppingCart'],
  },
  {
    name: 'shopping-bag',
    category: 'commerce',
    tags: ['bag', 'purchase', 'shop'],
    lucide: ['ShoppingBag'],
  },
  {
    name: 'receipt',
    category: 'commerce',
    tags: ['invoice', 'bill', 'order'],
    lucide: ['Receipt'],
  },
  { name: 'coins', category: 'commerce', tags: ['money', 'credits', 'usage'], lucide: ['Coins'] },
  { name: 'truck', category: 'commerce', tags: ['delivery', 'shipping'], lucide: ['Truck'] },
];
