// Builds the generated parts of the pack from its two sources of truth,
// `src/nodes.ts` (geometry) and `src/manifest.ts` (names, tags, lucide
// aliases):
//
//   src/react/icons.ts   the React components, one `createIcon` per icon
//   svg/<name>.svg       a standalone file per icon, for designers
//   svg/icons.json       the machine-readable manifest
//
// `node scripts/generate.ts` writes them. The unit test calls `validate` and
// `staleFiles`, so a geometry edit cannot ship without its generated files.

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

import { ICON_CATEGORIES, ICON_MANIFEST, type IconManifestEntry } from '../src/manifest.ts';
import * as nodes from '../src/nodes.ts';
import { ICON_DEFAULTS, iconToSvg, toCamel, toComponent } from '../src/svg.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SVG_DIR = 'svg';
const COMMAND = '`pnpm --filter @stunt-double/icons generate`';

const geometry = nodes as unknown as Record<string, unknown>;
const nodeKey = (entry: IconManifestEntry) => entry.node ?? toCamel(entry.name);
const node = (entry: IconManifestEntry) => geometry[nodeKey(entry)] as nodes.IconNode;

/** Every problem with the sources, as readable lines. Empty means sound. */
export function validate(): string[] {
  const errors: string[] = [];
  const names = new Set<string>();
  const lucide = new Map<string, string>();
  const used = new Set<string>();

  for (const entry of ICON_MANIFEST) {
    if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(entry.name))
      errors.push(`${entry.name}: name is not kebab-case`);
    if (names.has(entry.name)) errors.push(`${entry.name}: listed twice`);
    names.add(entry.name);
    if (!ICON_CATEGORIES.includes(entry.category))
      errors.push(`${entry.name}: unknown category ${entry.category}`);

    const key = nodeKey(entry);
    if (!Array.isArray(geometry[key]))
      errors.push(`${entry.name}: no geometry exported as \`${key}\` in nodes.ts`);
    used.add(key);

    for (const alias of entry.lucide) {
      if (lucide.has(alias))
        errors.push(`lucide ${alias}: mapped to both ${lucide.get(alias)} and ${entry.name}`);
      lucide.set(alias, entry.name);
    }
  }

  for (const [key, value] of Object.entries(geometry)) {
    if (Array.isArray(value) && !used.has(key))
      errors.push(`nodes.ts \`${key}\` has no manifest entry`);
  }
  return errors;
}

async function format(source: string, filepath: string): Promise<string> {
  const config = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(source, { ...config, filepath });
}

/** Every generated file, keyed by its path relative to the package root. */
export async function buildFiles(): Promise<Map<string, string>> {
  const files = new Map<string, string>();

  const components = ICON_MANIFEST.map(
    (entry) =>
      `export const ${toComponent(entry.name)} = /*#__PURE__*/ createIcon('${entry.name}', nodes.${nodeKey(entry)});`
  );
  const registry = ICON_MANIFEST.map((entry) => `  '${entry.name}': ${toComponent(entry.name)},`);
  const componentsPath = 'src/react/icons.ts';
  files.set(
    componentsPath,
    await format(
      [
        `// Generated by ${COMMAND} from \`nodes.ts\` and \`manifest.ts\`. Do not edit by hand.`,
        '',
        "import * as nodes from '../nodes.ts';",
        "import { createIcon, type IconComponent } from './create-icon.ts';",
        '',
        ...components,
        '',
        '/** Every icon by its kebab-case name, for lookups from data. */',
        'export const iconComponents: Record<string, IconComponent> = {',
        ...registry,
        '};',
        '',
      ].join('\n'),
      path.join(ROOT, componentsPath)
    )
  );

  for (const entry of ICON_MANIFEST) {
    files.set(`${SVG_DIR}/${entry.name}.svg`, iconToSvg(node(entry)));
  }

  const manifest = {
    $comment: `Generated by ${COMMAND}. Do not edit by hand.`,
    grid: {
      viewBox: '0 0 24 24',
      padding: 2,
      strokeWidth: ICON_DEFAULTS.strokeWidth,
      strokeLinecap: ICON_DEFAULTS.strokeLinecap,
      strokeLinejoin: ICON_DEFAULTS.strokeLinejoin,
      color: 'currentColor',
    },
    categories: ICON_CATEGORIES,
    icons: ICON_MANIFEST.map((entry) => ({
      name: entry.name,
      component: toComponent(entry.name),
      category: entry.category,
      tags: entry.tags,
      lucide: entry.lucide,
      file: `${entry.name}.svg`,
    })),
  };
  const manifestPath = `${SVG_DIR}/icons.json`;
  files.set(manifestPath, await format(JSON.stringify(manifest), path.join(ROOT, manifestPath)));

  return files;
}

/** Paths whose content on disk differs from what the build would write, plus strays. */
export async function staleFiles(): Promise<string[]> {
  const files = await buildFiles();
  const stale: string[] = [];
  for (const [relative, content] of files) {
    const current = await readFile(path.join(ROOT, relative), 'utf8').catch(() => null);
    if (current !== content) stale.push(relative);
  }
  const onDisk = await readdir(path.join(ROOT, SVG_DIR)).catch(() => []);
  for (const name of onDisk) {
    if (!files.has(`${SVG_DIR}/${name}`))
      stale.push(`${SVG_DIR}/${name} (no longer in the manifest)`);
  }
  return stale;
}

async function main() {
  const errors = validate();
  if (errors.length) {
    process.stderr.write(
      `Icon sources have ${errors.length} problem(s):\n  ${errors.join('\n  ')}\n`
    );
    process.exit(1);
  }
  const files = await buildFiles();
  await rm(path.join(ROOT, SVG_DIR), { recursive: true, force: true });
  await mkdir(path.join(ROOT, SVG_DIR), { recursive: true });
  for (const [relative, content] of files) {
    await writeFile(path.join(ROOT, relative), content);
  }
  process.stdout.write(`Wrote ${ICON_MANIFEST.length} icons.\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  await main();
}
