// Generated by `pnpm --filter @stunt-double/icons generate` from `brands.ts`. Do not edit by hand.

import * as brands from '../brands.ts';
import { createBrandIcon, type BrandIconComponent } from './create-brand-icon.ts';

export const ClaudeLogo = /*#__PURE__*/ createBrandIcon(brands.claude);
export const ClaudeCodeLogo = /*#__PURE__*/ createBrandIcon(brands.claudeCode);
export const AnthropicLogo = /*#__PURE__*/ createBrandIcon(brands.anthropic);
export const OpenaiLogo = /*#__PURE__*/ createBrandIcon(brands.openai);
export const CodexLogo = /*#__PURE__*/ createBrandIcon(brands.codex);
export const CursorLogo = /*#__PURE__*/ createBrandIcon(brands.cursor);
export const ClineLogo = /*#__PURE__*/ createBrandIcon(brands.cline);
export const WindsurfLogo = /*#__PURE__*/ createBrandIcon(brands.windsurf);
export const PerplexityLogo = /*#__PURE__*/ createBrandIcon(brands.perplexity);
export const GithubCopilotLogo = /*#__PURE__*/ createBrandIcon(brands.githubCopilot);
export const GeminiLogo = /*#__PURE__*/ createBrandIcon(brands.gemini);
export const MistralLogo = /*#__PURE__*/ createBrandIcon(brands.mistral);
export const DeepseekLogo = /*#__PURE__*/ createBrandIcon(brands.deepseek);
export const GrokLogo = /*#__PURE__*/ createBrandIcon(brands.grok);
export const V0Logo = /*#__PURE__*/ createBrandIcon(brands.v0);
export const LovableLogo = /*#__PURE__*/ createBrandIcon(brands.lovable);
export const ReplitLogo = /*#__PURE__*/ createBrandIcon(brands.replit);
export const OllamaLogo = /*#__PURE__*/ createBrandIcon(brands.ollama);
export const KiroLogo = /*#__PURE__*/ createBrandIcon(brands.kiro);
export const RooCodeLogo = /*#__PURE__*/ createBrandIcon(brands.rooCode);
export const KiloCodeLogo = /*#__PURE__*/ createBrandIcon(brands.kiloCode);
export const OpencodeLogo = /*#__PURE__*/ createBrandIcon(brands.opencode);
export const AmpLogo = /*#__PURE__*/ createBrandIcon(brands.amp);
export const DevinLogo = /*#__PURE__*/ createBrandIcon(brands.devin);
export const TraeLogo = /*#__PURE__*/ createBrandIcon(brands.trae);
export const JunieLogo = /*#__PURE__*/ createBrandIcon(brands.junie);
export const HuggingFaceLogo = /*#__PURE__*/ createBrandIcon(brands.huggingFace);
export const OpenrouterLogo = /*#__PURE__*/ createBrandIcon(brands.openrouter);
export const QwenLogo = /*#__PURE__*/ createBrandIcon(brands.qwen);

/** Every brand mark by its kebab-case name, for lookups from data. */
export const brandComponents: Record<string, BrandIconComponent> = {
  claude: ClaudeLogo,
  'claude-code': ClaudeCodeLogo,
  anthropic: AnthropicLogo,
  openai: OpenaiLogo,
  codex: CodexLogo,
  cursor: CursorLogo,
  cline: ClineLogo,
  windsurf: WindsurfLogo,
  perplexity: PerplexityLogo,
  'github-copilot': GithubCopilotLogo,
  gemini: GeminiLogo,
  mistral: MistralLogo,
  deepseek: DeepseekLogo,
  grok: GrokLogo,
  v0: V0Logo,
  lovable: LovableLogo,
  replit: ReplitLogo,
  ollama: OllamaLogo,
  kiro: KiroLogo,
  'roo-code': RooCodeLogo,
  'kilo-code': KiloCodeLogo,
  opencode: OpencodeLogo,
  amp: AmpLogo,
  devin: DevinLogo,
  trae: TraeLogo,
  junie: JunieLogo,
  'hugging-face': HuggingFaceLogo,
  openrouter: OpenrouterLogo,
  qwen: QwenLogo,
};
