// Generated by `pnpm --filter @stunt-double/icons generate` from `nodes.ts` and `manifest.ts`. Do not edit by hand.

import * as nodes from '../nodes.ts';
import { createIcon, type IconComponent } from './create-icon.ts';

export const ActorIcon = /*#__PURE__*/ createIcon('actor', nodes.actor);
export const ChecklistIcon = /*#__PURE__*/ createIcon('checklist', nodes.checklist);
export const RunIcon = /*#__PURE__*/ createIcon('run', nodes.run);
export const InterviewIcon = /*#__PURE__*/ createIcon('interview', nodes.interview);
export const AutomationIcon = /*#__PURE__*/ createIcon('automation', nodes.automation);
export const EvidenceIcon = /*#__PURE__*/ createIcon('evidence', nodes.evidence);
export const InsightIcon = /*#__PURE__*/ createIcon('insight', nodes.insight);
export const FeedbackIcon = /*#__PURE__*/ createIcon('feedback', nodes.feedback);
export const WorkerIcon = /*#__PURE__*/ createIcon('worker', nodes.worker);
export const ProjectIcon = /*#__PURE__*/ createIcon('project', nodes.project);
export const KnowledgeIcon = /*#__PURE__*/ createIcon('knowledge', nodes.knowledge);
export const TakeIcon = /*#__PURE__*/ createIcon('take', nodes.take);
export const LiveViewIcon = /*#__PURE__*/ createIcon('live-view', nodes.liveView);
export const DesignReviewIcon = /*#__PURE__*/ createIcon('design-review', nodes.designReview);
export const TopologyIcon = /*#__PURE__*/ createIcon('topology', nodes.topology);
export const StepIcon = /*#__PURE__*/ createIcon('step', nodes.step);
export const AssistIcon = /*#__PURE__*/ createIcon('assist', nodes.assist);
export const ArrowRightIcon = /*#__PURE__*/ createIcon('arrow-right', nodes.arrowRight);
export const ArrowLeftIcon = /*#__PURE__*/ createIcon('arrow-left', nodes.arrowLeft);
export const ArrowUpIcon = /*#__PURE__*/ createIcon('arrow-up', nodes.arrowUp);
export const ArrowDownIcon = /*#__PURE__*/ createIcon('arrow-down', nodes.arrowDown);
export const ArrowUpRightIcon = /*#__PURE__*/ createIcon('arrow-up-right', nodes.arrowUpRight);
export const ArrowDownRightIcon = /*#__PURE__*/ createIcon(
  'arrow-down-right',
  nodes.arrowDownRight
);
export const ArrowUpDownIcon = /*#__PURE__*/ createIcon('arrow-up-down', nodes.arrowUpDown);
export const ArrowDownUpIcon = /*#__PURE__*/ createIcon('arrow-down-up', nodes.arrowDownUp);
export const ChevronRightIcon = /*#__PURE__*/ createIcon('chevron-right', nodes.chevronRight);
export const ChevronLeftIcon = /*#__PURE__*/ createIcon('chevron-left', nodes.chevronLeft);
export const ChevronUpIcon = /*#__PURE__*/ createIcon('chevron-up', nodes.chevronUp);
export const ChevronDownIcon = /*#__PURE__*/ createIcon('chevron-down', nodes.chevronDown);
export const ChevronsUpDownIcon = /*#__PURE__*/ createIcon(
  'chevrons-up-down',
  nodes.chevronsUpDown
);
export const ChevronsDownUpIcon = /*#__PURE__*/ createIcon(
  'chevrons-down-up',
  nodes.chevronsDownUp
);
export const CornerDownLeftIcon = /*#__PURE__*/ createIcon(
  'corner-down-left',
  nodes.cornerDownLeft
);
export const ExternalLinkIcon = /*#__PURE__*/ createIcon('external-link', nodes.externalLink);
export const TrendingUpIcon = /*#__PURE__*/ createIcon('trending-up', nodes.trendingUp);
export const TrendingDownIcon = /*#__PURE__*/ createIcon('trending-down', nodes.trendingDown);
export const RefreshIcon = /*#__PURE__*/ createIcon('refresh', nodes.refresh);
export const RotateCcwIcon = /*#__PURE__*/ createIcon('rotate-ccw', nodes.rotateCcw);
export const RotateCwIcon = /*#__PURE__*/ createIcon('rotate-cw', nodes.rotateCw);
export const RepeatIcon = /*#__PURE__*/ createIcon('repeat', nodes.repeat);
export const HistoryIcon = /*#__PURE__*/ createIcon('history', nodes.history);
export const ShrinkIcon = /*#__PURE__*/ createIcon('shrink', nodes.shrink);
export const ExpandIcon = /*#__PURE__*/ createIcon('expand', nodes.expand);
export const NavigationIcon = /*#__PURE__*/ createIcon('navigation', nodes.navigation);
export const PlusIcon = /*#__PURE__*/ createIcon('plus', nodes.plus);
export const MinusIcon = /*#__PURE__*/ createIcon('minus', nodes.minus);
export const XIcon = /*#__PURE__*/ createIcon('x', nodes.x);
export const CheckIcon = /*#__PURE__*/ createIcon('check', nodes.check);
export const SearchIcon = /*#__PURE__*/ createIcon('search', nodes.search);
export const SearchXIcon = /*#__PURE__*/ createIcon('search-x', nodes.searchX);
export const ScanSearchIcon = /*#__PURE__*/ createIcon('scan-search', nodes.scanSearch);
export const TrashIcon = /*#__PURE__*/ createIcon('trash', nodes.trash);
export const CopyIcon = /*#__PURE__*/ createIcon('copy', nodes.copy);
export const ClipboardIcon = /*#__PURE__*/ createIcon('clipboard', nodes.clipboard);
export const ClipboardCheckIcon = /*#__PURE__*/ createIcon('clipboard-check', nodes.clipboardCheck);
export const ClipboardListIcon = /*#__PURE__*/ createIcon('clipboard-list', nodes.clipboardList);
export const ClipboardCopyIcon = /*#__PURE__*/ createIcon('clipboard-copy', nodes.clipboardCopy);
export const PencilIcon = /*#__PURE__*/ createIcon('pencil', nodes.pencil);
export const PencilLineIcon = /*#__PURE__*/ createIcon('pencil-line', nodes.pencilLine);
export const EditIcon = /*#__PURE__*/ createIcon('edit', nodes.edit);
export const DownloadIcon = /*#__PURE__*/ createIcon('download', nodes.download);
export const UploadIcon = /*#__PURE__*/ createIcon('upload', nodes.upload);
export const SendIcon = /*#__PURE__*/ createIcon('send', nodes.send);
export const ShareIcon = /*#__PURE__*/ createIcon('share', nodes.share);
export const LinkIcon = /*#__PURE__*/ createIcon('link', nodes.link);
export const LinkOffIcon = /*#__PURE__*/ createIcon('link-off', nodes.linkOff);
export const FilterIcon = /*#__PURE__*/ createIcon('filter', nodes.filter);
export const ListFilterIcon = /*#__PURE__*/ createIcon('list-filter', nodes.listFilter);
export const SlidersIcon = /*#__PURE__*/ createIcon('sliders', nodes.sliders);
export const ArchiveIcon = /*#__PURE__*/ createIcon('archive', nodes.archive);
export const ArchiveRestoreIcon = /*#__PURE__*/ createIcon('archive-restore', nodes.archiveRestore);
export const LogOutIcon = /*#__PURE__*/ createIcon('log-out', nodes.logOut);
export const DoorOpenIcon = /*#__PURE__*/ createIcon('door-open', nodes.doorOpen);
export const PrinterIcon = /*#__PURE__*/ createIcon('printer', nodes.printer);
export const PaperclipIcon = /*#__PURE__*/ createIcon('paperclip', nodes.paperclip);
export const GripVerticalIcon = /*#__PURE__*/ createIcon('grip-vertical', nodes.gripVertical);
export const MoreHorizontalIcon = /*#__PURE__*/ createIcon('more-horizontal', nodes.moreHorizontal);
export const MoreVerticalIcon = /*#__PURE__*/ createIcon('more-vertical', nodes.moreVertical);
export const BookmarkIcon = /*#__PURE__*/ createIcon('bookmark', nodes.bookmark);
export const BookmarkPlusIcon = /*#__PURE__*/ createIcon('bookmark-plus', nodes.bookmarkPlus);
export const TagIcon = /*#__PURE__*/ createIcon('tag', nodes.tag);
export const SparklesIcon = /*#__PURE__*/ createIcon('sparkles', nodes.sparkles);
export const WandIcon = /*#__PURE__*/ createIcon('wand', nodes.wand);
export const PlayIcon = /*#__PURE__*/ createIcon('play', nodes.play);
export const PlayCircleIcon = /*#__PURE__*/ createIcon('play-circle', nodes.playCircle);
export const PauseIcon = /*#__PURE__*/ createIcon('pause', nodes.pause);
export const StopIcon = /*#__PURE__*/ createIcon('stop', nodes.stop);
export const HandIcon = /*#__PURE__*/ createIcon('hand', nodes.hand);
export const PointerIcon = /*#__PURE__*/ createIcon('pointer', nodes.pointer);
export const PointerClickIcon = /*#__PURE__*/ createIcon('pointer-click', nodes.pointerClick);
export const PendingIcon = /*#__PURE__*/ createIcon('pending', nodes.pending);
export const CircleIcon = /*#__PURE__*/ createIcon('circle', nodes.circle);
export const CircleDotIcon = /*#__PURE__*/ createIcon('circle-dot', nodes.circleDot);
export const CircleDashedIcon = /*#__PURE__*/ createIcon('circle-dashed', nodes.circleDashed);
export const SquareIcon = /*#__PURE__*/ createIcon('square', nodes.square);
export const CheckCircleIcon = /*#__PURE__*/ createIcon('check-circle', nodes.checkCircle);
export const XCircleIcon = /*#__PURE__*/ createIcon('x-circle', nodes.xCircle);
export const MinusCircleIcon = /*#__PURE__*/ createIcon('minus-circle', nodes.minusCircle);
export const PlusCircleIcon = /*#__PURE__*/ createIcon('plus-circle', nodes.plusCircle);
export const InfoIcon = /*#__PURE__*/ createIcon('info', nodes.info);
export const HelpIcon = /*#__PURE__*/ createIcon('help', nodes.help);
export const AlertCircleIcon = /*#__PURE__*/ createIcon('alert-circle', nodes.alertCircle);
export const AlertTriangleIcon = /*#__PURE__*/ createIcon('alert-triangle', nodes.alertTriangle);
export const OctagonXIcon = /*#__PURE__*/ createIcon('octagon-x', nodes.octagonX);
export const BanIcon = /*#__PURE__*/ createIcon('ban', nodes.ban);
export const BadgeCheckIcon = /*#__PURE__*/ createIcon('badge-check', nodes.badgeCheck);
export const FlagIcon = /*#__PURE__*/ createIcon('flag', nodes.flag);
export const BellIcon = /*#__PURE__*/ createIcon('bell', nodes.bell);
export const BellRingIcon = /*#__PURE__*/ createIcon('bell-ring', nodes.bellRing);
export const ClockIcon = /*#__PURE__*/ createIcon('clock', nodes.clock);
export const CalendarIcon = /*#__PURE__*/ createIcon('calendar', nodes.calendar);
export const CalendarClockIcon = /*#__PURE__*/ createIcon('calendar-clock', nodes.calendarClock);
export const TimerIcon = /*#__PURE__*/ createIcon('timer', nodes.timer);
export const GaugeIcon = /*#__PURE__*/ createIcon('gauge', nodes.gauge);
export const MenuIcon = /*#__PURE__*/ createIcon('menu', nodes.menu);
export const SettingsIcon = /*#__PURE__*/ createIcon('settings', nodes.settings);
export const LayoutDashboardIcon = /*#__PURE__*/ createIcon(
  'layout-dashboard',
  nodes.layoutDashboard
);
export const LayoutGridIcon = /*#__PURE__*/ createIcon('layout-grid', nodes.layoutGrid);
export const ListIcon = /*#__PURE__*/ createIcon('list', nodes.list);
export const ListChecksIcon = /*#__PURE__*/ createIcon('list-checks', nodes.listChecks);
export const SquareCheckIcon = /*#__PURE__*/ createIcon('square-check', nodes.squareCheck);
export const SquareKanbanIcon = /*#__PURE__*/ createIcon('square-kanban', nodes.squareKanban);
export const AppWindowIcon = /*#__PURE__*/ createIcon('app-window', nodes.appWindow);
export const PanelsTopLeftIcon = /*#__PURE__*/ createIcon('panels-top-left', nodes.panelsTopLeft);
export const PanelRightOpenIcon = /*#__PURE__*/ createIcon(
  'panel-right-open',
  nodes.panelRightOpen
);
export const PanelRightCloseIcon = /*#__PURE__*/ createIcon(
  'panel-right-close',
  nodes.panelRightClose
);
export const FrameIcon = /*#__PURE__*/ createIcon('frame', nodes.frame);
export const LayersIcon = /*#__PURE__*/ createIcon('layers', nodes.layers);
export const BlocksIcon = /*#__PURE__*/ createIcon('blocks', nodes.blocks);
export const ComponentIcon = /*#__PURE__*/ createIcon('component', nodes.component);
export const KeyboardIcon = /*#__PURE__*/ createIcon('keyboard', nodes.keyboard);
export const CommandIcon = /*#__PURE__*/ createIcon('command', nodes.command);
export const HashIcon = /*#__PURE__*/ createIcon('hash', nodes.hash);
export const TypeIcon = /*#__PURE__*/ createIcon('type', nodes.type);
export const TextCursorInputIcon = /*#__PURE__*/ createIcon(
  'text-cursor-input',
  nodes.textCursorInput
);
export const FormInputIcon = /*#__PURE__*/ createIcon('form-input', nodes.formInput);
export const SunIcon = /*#__PURE__*/ createIcon('sun', nodes.sun);
export const MoonIcon = /*#__PURE__*/ createIcon('moon', nodes.moon);
export const ContrastIcon = /*#__PURE__*/ createIcon('contrast', nodes.contrast);
export const PaletteIcon = /*#__PURE__*/ createIcon('palette', nodes.palette);
export const AccessibilityIcon = /*#__PURE__*/ createIcon('accessibility', nodes.accessibility);
export const LanguagesIcon = /*#__PURE__*/ createIcon('languages', nodes.languages);
export const MessageSquareIcon = /*#__PURE__*/ createIcon('message-square', nodes.messageSquare);
export const MessageSquareTextIcon = /*#__PURE__*/ createIcon(
  'message-square-text',
  nodes.messageSquareText
);
export const MessageSquareMoreIcon = /*#__PURE__*/ createIcon(
  'message-square-more',
  nodes.messageSquareMore
);
export const MessageSquarePlusIcon = /*#__PURE__*/ createIcon(
  'message-square-plus',
  nodes.messageSquarePlus
);
export const MessagesSquareIcon = /*#__PURE__*/ createIcon('messages-square', nodes.messagesSquare);
export const QuoteIcon = /*#__PURE__*/ createIcon('quote', nodes.quote);
export const MessageCircleIcon = /*#__PURE__*/ createIcon('message-circle', nodes.messageCircle);
export const MailIcon = /*#__PURE__*/ createIcon('mail', nodes.mail);
export const MailOpenIcon = /*#__PURE__*/ createIcon('mail-open', nodes.mailOpen);
export const InboxIcon = /*#__PURE__*/ createIcon('inbox', nodes.inbox);
export const MegaphoneIcon = /*#__PURE__*/ createIcon('megaphone', nodes.megaphone);
export const GlobeIcon = /*#__PURE__*/ createIcon('globe', nodes.globe);
export const LifeBuoyIcon = /*#__PURE__*/ createIcon('life-buoy', nodes.lifeBuoy);
export const UserIcon = /*#__PURE__*/ createIcon('user', nodes.user);
export const UsersIcon = /*#__PURE__*/ createIcon('users', nodes.users);
export const UserPlusIcon = /*#__PURE__*/ createIcon('user-plus', nodes.userPlus);
export const BotIcon = /*#__PURE__*/ createIcon('bot', nodes.bot);
export const BrainIcon = /*#__PURE__*/ createIcon('brain', nodes.brain);
export const FingerprintIcon = /*#__PURE__*/ createIcon('fingerprint', nodes.fingerprint);
export const ShieldIcon = /*#__PURE__*/ createIcon('shield', nodes.shield);
export const ShieldCheckIcon = /*#__PURE__*/ createIcon('shield-check', nodes.shieldCheck);
export const ShieldOffIcon = /*#__PURE__*/ createIcon('shield-off', nodes.shieldOff);
export const LockIcon = /*#__PURE__*/ createIcon('lock', nodes.lock);
export const LockOpenIcon = /*#__PURE__*/ createIcon('lock-open', nodes.lockOpen);
export const KeyIcon = /*#__PURE__*/ createIcon('key', nodes.key);
export const EyeIcon = /*#__PURE__*/ createIcon('eye', nodes.eye);
export const EyeOffIcon = /*#__PURE__*/ createIcon('eye-off', nodes.eyeOff);
export const FileIcon = /*#__PURE__*/ createIcon('file', nodes.file);
export const FileTextIcon = /*#__PURE__*/ createIcon('file-text', nodes.fileText);
export const FileCheckIcon = /*#__PURE__*/ createIcon('file-check', nodes.fileCheck);
export const FileChartIcon = /*#__PURE__*/ createIcon('file-chart', nodes.fileChart);
export const FileJsonIcon = /*#__PURE__*/ createIcon('file-json', nodes.fileJson);
export const FileSearchIcon = /*#__PURE__*/ createIcon('file-search', nodes.fileSearch);
export const FilePenIcon = /*#__PURE__*/ createIcon('file-pen', nodes.filePen);
export const FolderIcon = /*#__PURE__*/ createIcon('folder', nodes.folder);
export const FolderPlusIcon = /*#__PURE__*/ createIcon('folder-plus', nodes.folderPlus);
export const FolderKanbanIcon = /*#__PURE__*/ createIcon('folder-kanban', nodes.folderKanban);
export const BookOpenIcon = /*#__PURE__*/ createIcon('book-open', nodes.bookOpen);
export const BookMarkedIcon = /*#__PURE__*/ createIcon('book-marked', nodes.bookMarked);
export const LibraryIcon = /*#__PURE__*/ createIcon('library', nodes.library);
export const NewspaperIcon = /*#__PURE__*/ createIcon('newspaper', nodes.newspaper);
export const ScrollTextIcon = /*#__PURE__*/ createIcon('scroll-text', nodes.scrollText);
export const ImageIcon = /*#__PURE__*/ createIcon('image', nodes.image);
export const ImagePlusIcon = /*#__PURE__*/ createIcon('image-plus', nodes.imagePlus);
export const CameraIcon = /*#__PURE__*/ createIcon('camera', nodes.camera);
export const MicIcon = /*#__PURE__*/ createIcon('mic', nodes.mic);
export const FilmIcon = /*#__PURE__*/ createIcon('film', nodes.film);
export const ClapperboardIcon = /*#__PURE__*/ createIcon('clapperboard', nodes.clapperboard);
export const MonitorPlayIcon = /*#__PURE__*/ createIcon('monitor-play', nodes.monitorPlay);
export const PenToolIcon = /*#__PURE__*/ createIcon('pen-tool', nodes.penTool);
export const RulerIcon = /*#__PURE__*/ createIcon('ruler', nodes.ruler);
export const MonitorIcon = /*#__PURE__*/ createIcon('monitor', nodes.monitor);
export const MonitorOffIcon = /*#__PURE__*/ createIcon('monitor-off', nodes.monitorOff);
export const SmartphoneIcon = /*#__PURE__*/ createIcon('smartphone', nodes.smartphone);
export const TabletIcon = /*#__PURE__*/ createIcon('tablet', nodes.tablet);
export const ServerIcon = /*#__PURE__*/ createIcon('server', nodes.server);
export const DatabaseIcon = /*#__PURE__*/ createIcon('database', nodes.database);
export const ChartBarIcon = /*#__PURE__*/ createIcon('chart-bar', nodes.chartBar);
export const ChartColumnIcon = /*#__PURE__*/ createIcon('chart-column', nodes.chartColumn);
export const ChartLineIcon = /*#__PURE__*/ createIcon('chart-line', nodes.chartLine);
export const ActivityIcon = /*#__PURE__*/ createIcon('activity', nodes.activity);
export const TargetIcon = /*#__PURE__*/ createIcon('target', nodes.target);
export const TerminalIcon = /*#__PURE__*/ createIcon('terminal', nodes.terminal);
export const SquareTerminalIcon = /*#__PURE__*/ createIcon('square-terminal', nodes.squareTerminal);
export const CodeIcon = /*#__PURE__*/ createIcon('code', nodes.code);
export const GitBranchIcon = /*#__PURE__*/ createIcon('git-branch', nodes.gitBranch);
export const GitPullRequestIcon = /*#__PURE__*/ createIcon(
  'git-pull-request',
  nodes.gitPullRequest
);
export const WorkflowIcon = /*#__PURE__*/ createIcon('workflow', nodes.workflow);
export const NetworkIcon = /*#__PURE__*/ createIcon('network', nodes.network);
export const RouteIcon = /*#__PURE__*/ createIcon('route', nodes.route);
export const PlugIcon = /*#__PURE__*/ createIcon('plug', nodes.plug);
export const BugIcon = /*#__PURE__*/ createIcon('bug', nodes.bug);
export const PackageIcon = /*#__PURE__*/ createIcon('package', nodes.packageBox);
export const FlaskIcon = /*#__PURE__*/ createIcon('flask', nodes.flask);
export const WrenchIcon = /*#__PURE__*/ createIcon('wrench', nodes.wrench);
export const RocketIcon = /*#__PURE__*/ createIcon('rocket', nodes.rocket);
export const ZapIcon = /*#__PURE__*/ createIcon('zap', nodes.zap);
export const HomeIcon = /*#__PURE__*/ createIcon('home', nodes.home);
export const BuildingIcon = /*#__PURE__*/ createIcon('building', nodes.building);
export const BuildingsIcon = /*#__PURE__*/ createIcon('buildings', nodes.buildings);
export const StoreIcon = /*#__PURE__*/ createIcon('store', nodes.store);
export const MapPinIcon = /*#__PURE__*/ createIcon('map-pin', nodes.mapPin);
export const CompassIcon = /*#__PURE__*/ createIcon('compass', nodes.compass);
export const ScaleIcon = /*#__PURE__*/ createIcon('scale', nodes.scale);
export const BrickWallIcon = /*#__PURE__*/ createIcon('brick-wall', nodes.brickWall);
export const LightbulbIcon = /*#__PURE__*/ createIcon('lightbulb', nodes.lightbulb);
export const GiftIcon = /*#__PURE__*/ createIcon('gift', nodes.gift);
export const FlameIcon = /*#__PURE__*/ createIcon('flame', nodes.flame);
export const CreditCardIcon = /*#__PURE__*/ createIcon('credit-card', nodes.creditCard);
export const ShoppingCartIcon = /*#__PURE__*/ createIcon('shopping-cart', nodes.shoppingCart);
export const ShoppingBagIcon = /*#__PURE__*/ createIcon('shopping-bag', nodes.shoppingBag);
export const ReceiptIcon = /*#__PURE__*/ createIcon('receipt', nodes.receipt);
export const CoinsIcon = /*#__PURE__*/ createIcon('coins', nodes.coins);
export const TruckIcon = /*#__PURE__*/ createIcon('truck', nodes.truck);

/** Every icon by its kebab-case name, for lookups from data. */
export const iconComponents: Record<string, IconComponent> = {
  actor: ActorIcon,
  checklist: ChecklistIcon,
  run: RunIcon,
  interview: InterviewIcon,
  automation: AutomationIcon,
  evidence: EvidenceIcon,
  insight: InsightIcon,
  feedback: FeedbackIcon,
  worker: WorkerIcon,
  project: ProjectIcon,
  knowledge: KnowledgeIcon,
  take: TakeIcon,
  'live-view': LiveViewIcon,
  'design-review': DesignReviewIcon,
  topology: TopologyIcon,
  step: StepIcon,
  assist: AssistIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-up-right': ArrowUpRightIcon,
  'arrow-down-right': ArrowDownRightIcon,
  'arrow-up-down': ArrowUpDownIcon,
  'arrow-down-up': ArrowDownUpIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-down': ChevronDownIcon,
  'chevrons-up-down': ChevronsUpDownIcon,
  'chevrons-down-up': ChevronsDownUpIcon,
  'corner-down-left': CornerDownLeftIcon,
  'external-link': ExternalLinkIcon,
  'trending-up': TrendingUpIcon,
  'trending-down': TrendingDownIcon,
  refresh: RefreshIcon,
  'rotate-ccw': RotateCcwIcon,
  'rotate-cw': RotateCwIcon,
  repeat: RepeatIcon,
  history: HistoryIcon,
  shrink: ShrinkIcon,
  expand: ExpandIcon,
  navigation: NavigationIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  x: XIcon,
  check: CheckIcon,
  search: SearchIcon,
  'search-x': SearchXIcon,
  'scan-search': ScanSearchIcon,
  trash: TrashIcon,
  copy: CopyIcon,
  clipboard: ClipboardIcon,
  'clipboard-check': ClipboardCheckIcon,
  'clipboard-list': ClipboardListIcon,
  'clipboard-copy': ClipboardCopyIcon,
  pencil: PencilIcon,
  'pencil-line': PencilLineIcon,
  edit: EditIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  send: SendIcon,
  share: ShareIcon,
  link: LinkIcon,
  'link-off': LinkOffIcon,
  filter: FilterIcon,
  'list-filter': ListFilterIcon,
  sliders: SlidersIcon,
  archive: ArchiveIcon,
  'archive-restore': ArchiveRestoreIcon,
  'log-out': LogOutIcon,
  'door-open': DoorOpenIcon,
  printer: PrinterIcon,
  paperclip: PaperclipIcon,
  'grip-vertical': GripVerticalIcon,
  'more-horizontal': MoreHorizontalIcon,
  'more-vertical': MoreVerticalIcon,
  bookmark: BookmarkIcon,
  'bookmark-plus': BookmarkPlusIcon,
  tag: TagIcon,
  sparkles: SparklesIcon,
  wand: WandIcon,
  play: PlayIcon,
  'play-circle': PlayCircleIcon,
  pause: PauseIcon,
  stop: StopIcon,
  hand: HandIcon,
  pointer: PointerIcon,
  'pointer-click': PointerClickIcon,
  pending: PendingIcon,
  circle: CircleIcon,
  'circle-dot': CircleDotIcon,
  'circle-dashed': CircleDashedIcon,
  square: SquareIcon,
  'check-circle': CheckCircleIcon,
  'x-circle': XCircleIcon,
  'minus-circle': MinusCircleIcon,
  'plus-circle': PlusCircleIcon,
  info: InfoIcon,
  help: HelpIcon,
  'alert-circle': AlertCircleIcon,
  'alert-triangle': AlertTriangleIcon,
  'octagon-x': OctagonXIcon,
  ban: BanIcon,
  'badge-check': BadgeCheckIcon,
  flag: FlagIcon,
  bell: BellIcon,
  'bell-ring': BellRingIcon,
  clock: ClockIcon,
  calendar: CalendarIcon,
  'calendar-clock': CalendarClockIcon,
  timer: TimerIcon,
  gauge: GaugeIcon,
  menu: MenuIcon,
  settings: SettingsIcon,
  'layout-dashboard': LayoutDashboardIcon,
  'layout-grid': LayoutGridIcon,
  list: ListIcon,
  'list-checks': ListChecksIcon,
  'square-check': SquareCheckIcon,
  'square-kanban': SquareKanbanIcon,
  'app-window': AppWindowIcon,
  'panels-top-left': PanelsTopLeftIcon,
  'panel-right-open': PanelRightOpenIcon,
  'panel-right-close': PanelRightCloseIcon,
  frame: FrameIcon,
  layers: LayersIcon,
  blocks: BlocksIcon,
  component: ComponentIcon,
  keyboard: KeyboardIcon,
  command: CommandIcon,
  hash: HashIcon,
  type: TypeIcon,
  'text-cursor-input': TextCursorInputIcon,
  'form-input': FormInputIcon,
  sun: SunIcon,
  moon: MoonIcon,
  contrast: ContrastIcon,
  palette: PaletteIcon,
  accessibility: AccessibilityIcon,
  languages: LanguagesIcon,
  'message-square': MessageSquareIcon,
  'message-square-text': MessageSquareTextIcon,
  'message-square-more': MessageSquareMoreIcon,
  'message-square-plus': MessageSquarePlusIcon,
  'messages-square': MessagesSquareIcon,
  quote: QuoteIcon,
  'message-circle': MessageCircleIcon,
  mail: MailIcon,
  'mail-open': MailOpenIcon,
  inbox: InboxIcon,
  megaphone: MegaphoneIcon,
  globe: GlobeIcon,
  'life-buoy': LifeBuoyIcon,
  user: UserIcon,
  users: UsersIcon,
  'user-plus': UserPlusIcon,
  bot: BotIcon,
  brain: BrainIcon,
  fingerprint: FingerprintIcon,
  shield: ShieldIcon,
  'shield-check': ShieldCheckIcon,
  'shield-off': ShieldOffIcon,
  lock: LockIcon,
  'lock-open': LockOpenIcon,
  key: KeyIcon,
  eye: EyeIcon,
  'eye-off': EyeOffIcon,
  file: FileIcon,
  'file-text': FileTextIcon,
  'file-check': FileCheckIcon,
  'file-chart': FileChartIcon,
  'file-json': FileJsonIcon,
  'file-search': FileSearchIcon,
  'file-pen': FilePenIcon,
  folder: FolderIcon,
  'folder-plus': FolderPlusIcon,
  'folder-kanban': FolderKanbanIcon,
  'book-open': BookOpenIcon,
  'book-marked': BookMarkedIcon,
  library: LibraryIcon,
  newspaper: NewspaperIcon,
  'scroll-text': ScrollTextIcon,
  image: ImageIcon,
  'image-plus': ImagePlusIcon,
  camera: CameraIcon,
  mic: MicIcon,
  film: FilmIcon,
  clapperboard: ClapperboardIcon,
  'monitor-play': MonitorPlayIcon,
  'pen-tool': PenToolIcon,
  ruler: RulerIcon,
  monitor: MonitorIcon,
  'monitor-off': MonitorOffIcon,
  smartphone: SmartphoneIcon,
  tablet: TabletIcon,
  server: ServerIcon,
  database: DatabaseIcon,
  'chart-bar': ChartBarIcon,
  'chart-column': ChartColumnIcon,
  'chart-line': ChartLineIcon,
  activity: ActivityIcon,
  target: TargetIcon,
  terminal: TerminalIcon,
  'square-terminal': SquareTerminalIcon,
  code: CodeIcon,
  'git-branch': GitBranchIcon,
  'git-pull-request': GitPullRequestIcon,
  workflow: WorkflowIcon,
  network: NetworkIcon,
  route: RouteIcon,
  plug: PlugIcon,
  bug: BugIcon,
  package: PackageIcon,
  flask: FlaskIcon,
  wrench: WrenchIcon,
  rocket: RocketIcon,
  zap: ZapIcon,
  home: HomeIcon,
  building: BuildingIcon,
  buildings: BuildingsIcon,
  store: StoreIcon,
  'map-pin': MapPinIcon,
  compass: CompassIcon,
  scale: ScaleIcon,
  'brick-wall': BrickWallIcon,
  lightbulb: LightbulbIcon,
  gift: GiftIcon,
  flame: FlameIcon,
  'credit-card': CreditCardIcon,
  'shopping-cart': ShoppingCartIcon,
  'shopping-bag': ShoppingBagIcon,
  receipt: ReceiptIcon,
  coins: CoinsIcon,
  truck: TruckIcon,
};
